FROM golang:1.18.4-alpine

RUN apk update && apk upgrade && \
    apk add git curl \
    make openssh-client

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download && go mod verify

RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

CMD ["air"]
