name: build backend
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.1'
      - name: Install dependencies
        run: |
          go version
          cd ./backend/ && go mod download
      - name: Build
        run: cd backend && go build ./app/main.go
