name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: ls -a via ssh
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          command: |
            cd ${{ secrets.SSH_TARGET }}
            eval $(ssh-agent -s)
            ssh-add ~/.ssh/github
            cd second-brain
            git fetch --all
            git reset --hard origin/master
            git submodule update --recursive --remote
            docker-compose -f docker-compose.yaml -f docker-compose.prod.yaml up --build -d
